from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support.ui import Select
import time
driver = webdriver.Chrome(r"C:\Users\Jayendra\Desktop\Selenium\chromedriver_win32\chromedriver.exe")
driver.implicitly_wait(5)
driver.maximize_window()
# driver = webdriver.Ie(r"C:\Users\Jayendra\Desktop\Selenium\chromedriver_win32\IEDriverServer.exe")
driver.get("https://fs2.formsite.com/meherpavan/form2/index.html")
driver.implicitly_wait(5)
Inputboxes=driver.find_elements(By.CLASS_NAME,"text_field")
print(len(Inputboxes))
wait=WebDriverWait(driver,10)
# status_1=driver.find_element(By.ID,"RESULT_TextField-1").is_displayed()
# status_2=driver.find_element(By.ID,"RESULT_TextField-1").is_enabled()
# print(status_1)
# print(status_2)
# driver.find_element(By.ID,"RESULT_TextField-1").send_keys("Atul")
driver.find_element(By.ID,"RESULT_TextField-1").send_keys("Atul")
driver.find_element(By.ID,"RESULT_TextField-2").send_keys("Tripathi")
driver.find_element(By.XPATH,"//*[@id='q26']/table/tbody/tr[1]/td/label").click()
# driver.find_element(By.ID,"RESULT_RadioButton-7_0").click()
staus=driver.find_element(By.ID,"RESULT_RadioButton-7_0").is_selected()
print(staus)
driver.find_element(By.XPATH,"//*[@id='q15']/table/tbody/tr[1]/td/label").click()
driver.find_element(By.XPATH,"//*[@id='q15']/table/tbody/tr[7]/td/label").click()
element=driver.find_element_by_id("RESULT_RadioButton-9")
drp=Select(element)
# drp.select_by_visible_text('Afternoon')
# drp.select_by_index(2)
drp.select_by_value("Radio-0")
time.sleep(5)
driver.close()